### PR TITLE
fix error caused by catch(e)

### PR DESCRIPTION
**Pull request by MoZhonghua**
I compile with tsc  v4.4.3 and get this error:
```txt
test.ts:81:21 - error TS2571: Object is of type 'unknown'.
81         console.log(e.stack)
                       ~
Found 1 error.
```
After some searching, I found this: 
https://stackoverflow.com/questions/68240884/error-object-inside-catch-is-of-type-unkown

### CODE REVIEW

**Comment by josephg** [comment]
This package currently explicitly depends on typescript 4.2.

Can you either check your patch works with typescript 4.2 (use npx tsc) or update the dependency to typescript 4.4.x?
